### ISSUE TITLE
Error when dehaloing

### ISSUE THREAD

**Issue by lextra2** [DonCanjas/Avisynth-Functions#1]
![image](https://user-images.githubusercontent.com/20690384/191915970-82016bc4-ef23-4d42-b0ed-042904e1d273.png)

**Comment by DonCanjas** [comment]
You're missing Zs_RF_Shared.avsi. I should have listed every dependency in readme

**Comment by lextra2** [comment]
Uhm yeah. Would be nice if all dependencies are listed somewhere...

**Comment by DonCanjas** [comment]
> Uhm yeah. Would be nice if all dependencies are listed somewhere...

I already added it to the script itself.
